#!/bin/zsh

# Keep cursor at end of line
bindkey -e .safe

# home, end, delete
bindkey -e "[1~" beginning-of-line
bindkey -e "[4~" end-of-line
bindkey -e "[3~" delete-char

# allow for editing of the command line
# http://zshwiki.org/home/examples/zlewidgets
autoload -U    edit-command-line
zle -N         edit-command-line
bindkey -a 'v' edit-command-line

