#!/bin/zsh

# allow for editing of the command line
# http://zshwiki.org/home/examples/zlewidgets
autoload -U    edit-command-line
zle -N         edit-command-line
bindkey -a 'v' edit-command-line

typeset -A key

# Get keys from terminfo
key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[Up]=${terminfo[kcuu1]}
key[Down]=${terminfo[kcud1]}
key[Left]=${terminfo[kcub1]}
key[Right]=${terminfo[kcuf1]}
key[PageUp]=${terminfo[kpp]}
key[PageDown]=${terminfo[knp]}

# reprocess keys
for k in ${(k)key} ; do
	# $terminfo[] entries are weird in ncurses application mode...
	[[ ${key[$k]} == $'\eO'* ]] && key[$k]=${key[$k]/O/[}
done
unset k

# setup key accordingly
[[ -n "${key[Home]}"	]] && bindkey "${key[Home]}"	beginning-of-line
[[ -n "${key[End]}"		]] && bindkey "${key[End]}"		end-of-line
[[ -n "${key[Insert]}"	]] && bindkey "${key[Insert]}"	overwrite-mode
[[ -n "${key[Delete]}"	]] && bindkey "${key[Delete]}"	delete-char
[[ -n "${key[Up]}"		]] && bindkey "${key[Up]}"		up-line-or-history
[[ -n "${key[Down]}"	]] && bindkey "${key[Down]}"	down-line-or-history
[[ -n "${key[Left]}"	]] && bindkey "${key[Left]}"	backward-char
[[ -n "${key[Right]}"	]] && bindkey "${key[Right]}"	forward-char

