#!/bin/zsh

autoload colors zsh/terminfo
if [[ "$terminfo[colors]" -ge 8 ]]; then
	colors
fi

for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
	eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
	eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
	(( count = $count + 1 ))
done
PR_NO_COLOUR="%{$terminfo[sgr0]%}"


autoload -U promptinit
promptinit
setopt prompt_subst

function lprompt {
	PROMPT="%(!.$PR_RED.$PR_GREEN)%n@%m $PR_BLUE%~ $PR_MAGENTA$ $PR_NO_COLOUR"
}

function rprompt {
	local git_b git_s
	git_b='$(get_git_prompt_info '%b')'
	git_s='$(get_git_prompt_info '%s')'

	RPROMPT="$PR_RED$git_b$PR_MAGENTA$git_s$PR_NO_COLOUR"
}

rprompt
lprompt

